# Generated by Django 2.1.7 on 2019-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
